import { DEFAULT_EXCLUDED_DIRECTORIES, DEFAULT_SOURCE_EXTENSIONS, } from "@claudiu-ceia/astkit-core";
export const DEFAULT_SEARCHABLE_EXTENSIONS = DEFAULT_SOURCE_EXTENSIONS;
export const DEFAULT_SEARCH_EXCLUDED_DIRECTORIES = DEFAULT_EXCLUDED_DIRECTORIES;
